# This is a basic workflow to help you get started with Actions

name: build-frontend-and-push-docker-image

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master, main ]
#   pull_request:
#     branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  build-ghpage:
    permissions:
     id-token: write # required for actions/deploy-pages@v4
     pages: write

    # https://help.github.com/en/actions/reference/virtual-environments-for-github-hosted-runners#supported-runners-and-hardware-resources
    runs-on: ubuntu-latest
    environment:
        name: github-pages
    steps:

    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v4
    # https://github.com/actions/setup-node#usage
    - uses: actions/setup-node@v4
      with:
        node-version: '21.4.0'

    # Runs a set of commands using the runners shell
    - name: Build and publish Frontend (GH Page)
      env:
        GITHUB_REPOSITORY: ${{github.repository}}
        GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}
        GITHUB_TOKEN: ${{ secrets.github_token }}
        COMMIT_FILES: "./docs"
      run: |
        bash +x ./.github/workflows/build-ghpage.sh

    # Store the gh-pages as artifact
    # see https://docs.github.com/en/actions/using-workflows/storing-workflow-data-as-artifacts
    - name: Archive code coverage results
      uses: actions/upload-artifact@v4
      with:
        name: github-pages
        path: docs
    # Deploy it as ghpage
    # see https://github.com/actions/deploy-pages
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4


  push-docker:
    # permissions for GITHUB_TOKEN
    # see https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token
    permissions:
      packages: write

    # The type of runner that the job will run on
    # https://help.github.com/en/actions/reference/virtual-environments-for-github-hosted-runners#supported-runners-and-hardware-resources
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v4
    - name: Build and Push docker image
      env:
        GITHUB_REPOSITORY: ${{github.repository}}
        GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}
        # TOKEN_PUBLISH_PACKAGE: ${{ secrets.GITHUB_TOKEN }}
        TOKEN_PUBLISH_PACKAGE: ${{ secrets.TOKEN_PUBLISH_PACKAGE }}
        DOCKER_FILE: "./Dockerfile"
      run: |
        bash +x ./.github/workflows/push-docker-image.sh